const KEY='recorbet_batier_v1';let state=JSON.parse(localStorage.getItem(KEY)||'{"clients":[],"interventions":[],"stock":[]}');let current='home';const cfg=window.RECORBET_CONFIG||{};let cloud=null;
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function render(){document.querySelectorAll('.bottom button').forEach(b=>b.classList.toggle('active',b.dataset.view===current));let v=document.getElementById('view');v.innerHTML=current==='home'?home():current==='clients'?clients():current==='interventions'?interventions():stock();bind()}
function home(){let low=state.stock.filter(x=>x.depot+x.truck<=x.min).length;return `<section class="hero"><h1>Bonjour 👋</h1><div>Votre carnet de chantier</div><div class="actions"><button class="btn" data-action="new-intervention">+ Intervention</button><button class="btn secondary" data-action="new-client">+ Client</button></div></section><div class="grid"><div class="card"><div class="muted">Clients</div><div class="stat">${state.clients.length}</div></div><div class="card"><div class="muted">Interventions</div><div class="stat">${state.interventions.length}</div></div><div class="card"><div class="muted">Articles</div><div class="stat">${state.stock.length}</div></div><div class="card"><div class="muted">Alertes stock</div><div class="stat">${low}</div></div></div>${low?'<div class="alert"><strong>⚠️ Stock faible</strong><br>Ouvre la rubrique Stock pour voir les articles.</div>':''}`}
function clients(){return `<div class="section-title"><h2>Clients</h2><button class="btn" data-action="new-client">+ Ajouter</button></div><div class="list">${state.clients.length?state.clients.map(c=>`<div class="row"><div><strong>${esc(c.name)}</strong><div class="muted">${esc(c.phone||'')} ${c.address?'· '+esc(c.address):''}</div></div></div>`).join(''):'<div class="empty">Aucun client.</div>'}</div>`}
function interventions(){return `<div class="section-title"><h2>Interventions</h2><button class="btn" data-action="new-intervention">+ Ajouter</button></div><div class="list">${state.interventions.length?state.interventions.slice().reverse().map(i=>`<div class="row"><div><strong>${esc(i.title)}</strong><div class="muted">${esc(i.clientName||'')} · ${esc(i.date||'')}</div><span class="badge">${esc(i.type)}</span></div></div>`).join(''):'<div class="empty">Aucune intervention.</div>'}</div>`}
function stock(){let low=state.stock.filter(x=>x.depot+x.truck<=x.min);return `<div class="section-title"><h2>Stock</h2><button class="btn" data-action="new-stock">+ Article</button></div>${low.map(x=>`<div class="alert">⚠️ <strong>${esc(x.name)}</strong> — total ${x.depot+x.truck}, minimum ${x.min}</div>`).join('')}<div class="list">${state.stock.length?state.stock.map(x=>`<div class="row"><div><strong>${esc(x.name)}</strong><div class="muted">Dépôt ${x.depot} · Camion ${x.truck} · Total ${x.depot+x.truck}</div></div></div>`).join(''):'<div class="empty">Aucun article.</div>'}</div>`}
function modal(title,body){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><div class="sheet"><button class="close" onclick="document.getElementById('modal').remove()">✕</button><h2>${title}</h2>${body}</div></div>`)}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{current=b.dataset.view;render()});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action))}
function action(a){if(a==='new-client')modal('Nouveau client',`<form class="form" onsubmit="addClient(event)"><label>Nom / société<input name="name" required></label><label>Téléphone<input name="phone"></label><label>Adresse<textarea name="address"></textarea></label><label>Notes<textarea name="notes"></textarea></label><button class="btn">Enregistrer</button></form>`);if(a==='new-intervention')modal('Nouvelle intervention',`<form class="form" onsubmit="addInt(event)"><label>Client<select name="client">${state.clients.map(c=>`<option>${esc(c.name)}</option>`).join('')}</select></label><label>Intitulé<input name="title" placeholder="Ex. Recherche de fuite" required></label><label>Type<select name="type"><option>Plomberie</option><option>Chauffage</option><option>Entretien</option><option>Relevé de chantier</option><option>Travaux à faire</option></select></label><label>Date<input name="date" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Observations<textarea name="notes"></textarea></label><button class="btn">Enregistrer</button></form>`);if(a==='new-stock')modal('Nouvel article',`<form class="form" onsubmit="addStock(event)"><label>Désignation<input name="name" required></label><label>Unité<input name="unit" placeholder="pièce, m, boîte..."></label><label>Quantité dépôt<input name="depot" type="number" min="0" value="0"></label><label>Quantité camion<input name="truck" type="number" min="0" value="0"></label><label>Seuil d'alerte<input name="min" type="number" min="0" value="1"></label><button class="btn">Enregistrer</button></form>`)}
function addClient(e){e.preventDefault();let f=new FormData(e.target);state.clients.push({id:crypto.randomUUID(),name:f.get('name'),phone:f.get('phone'),address:f.get('address'),notes:f.get('notes')});save();document.getElementById('modal').remove()}
function addInt(e){e.preventDefault();let f=new FormData(e.target);state.interventions.push({id:crypto.randomUUID(),clientName:f.get('client'),title:f.get('title'),type:f.get('type'),date:f.get('date'),notes:f.get('notes')});save();document.getElementById('modal').remove()}
function addStock(e){e.preventDefault();let f=new FormData(e.target);state.stock.push({id:crypto.randomUUID(),name:f.get('name'),unit:f.get('unit'),depot:+f.get('depot'),truck:+f.get('truck'),min:+f.get('min')});save();document.getElementById('modal').remove()}
window.addEventListener('load',()=>{render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})});